language: java

sudo: false
#  to set a local hostname
addons:
  hosts:
    - db
#  services we want and tell to Travis
services:
  - docker

install:
  - docker build -t database db/.
  - docker run --rm -d -e MYSQL_ROOT_PASSWORD=example -p 33060:3306 database
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#  run before any script part of a job
before_script:
  - mvn clean

#build script
#script:
#  - mvn test -Dtest=com.napier.sem.AppTest

#  define build stages under a include item
jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.AppTest
    - stage: integration tests
      jdk: oraclejdk11
      script: echo "Integration Tests"
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"