version: '3'
services:
  # Application Dockerfile is in same folder which is .
  # it will run app.java file
  app:
    build: .

  # db is is db folder
  #location database
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always