'USE CASE: 8  Produce a report on the population of the people, living in the world, a continent, a region, a country, a district, a city
@startuml
'Delecare skinparam
skinparam packageStyle rectangle
'Declare actor as user
actor User
'Declare database as D for world sql
rectangle "World Database" as D

rectangle "Produce a report on the population of the people, living in the world, a continent, a region, a country, a district, a city" {
'Delcare usecase information
usecase UC1 as "Request for the population of the people by certain attributes"
usecase UC2 as "Query by certain area"
usecase UC3 as "View population information"

'Start usecase diagram
User --> UC1
'(start) -down-> UC1
UC1 .down.> UC2:include
UC2 .left. D
UC2 .down.> UC3
}

'End usecase diagram
@enduml