' USE CASE: 9 Generate a report on the number of people who speak different languages, and the percentage of the world population
@startuml
'Delecare skinparam
skinparam packageStyle rectangle
'Declare actor as user
actor User
'Declare database as D for world sql
rectangle "World Database" as D

rectangle "a report on the number of people who speak different languages, and the percentage of the world population" {
'Delcare usecase information
usecase UC1 as "Request the number of people by certain attributes"
usecase UC2 as "Query by certain area"
usecase UC3 as "View population information"

'Start usecase diagram
User --> UC1
'(start) -down-> UC1
UC1 .down.> UC2:include
UC2 .left. D
UC2 .down.> UC3
}

'End usecase diagram
@endum